---
- name: Config elk VM with Docker
  hosts: elk
  remote_user: azadmin
  become: true
  tasks:
  - name: "More memory for ELK"
    sysctl:
      name: vm.max_map_count
      reload: true
      state: present
      value: "262144"
  - name: docker.io
    apt:
      force_apt_get: true
      name: docker.io
      state: present
      update_cache: true
  - name: "Install pip3"
    apt:
      force_apt_get: true
      name: python3-pip
      state: present
  - name: "Install Docker python module"
    pip:
      name: docker
      state: present
  - name: "download and launch a docker web container"
    docker_container:
      image: sebp/elk:761
      name: elk
      ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044
      state: started
  - name: "Enable docker service"
    systemd:
      enabled: true
      name: docker
